### ISSUE TITLE
Vocabularies umbrella issue

### ISSUE THREAD

**Issue by dpancic** [SSHOC/vocabularies#17]
In GitLab by @laureD19 on May 19, 2021, 14:12

this issue lists the concept-based properties found in the [source of truth](https://docs.google.com/spreadsheets/d/17E6oJ_mXZFXNhQWhvOMmPLu5reJKImwI5OP44yudfe8/edit#gid=190660862). Separate issues (and a dedicated file in the repo when needed) will be created for each of the vocabularies used:

- [x] `activity` using TADIRaH (#4) -> https://gitlab.gwdg.de/sshoc/vocabularies/-/tree/master/tadirah
- [x] `geographical-availability` using EOSC vocabulary (#9 )
- [x] `language` using vocabulary: iso-639-3 (#5 ) 
- [x] `license` using vocabulary software-license (#7 ) -> https://gitlab.gwdg.de/sshoc/vocabularies/-/tree/master/licenses
- [x] `life-cycle-status` using EOSC vocabulary (#10 ) -> 
- [x] `mode-of-use` usine vocabulary: invocation-types (SSHOC WP3) -> https://gitlab.gwdg.de/sshoc/vocabularies/-/tree/master/invocation-types 
- [x] `object-format` vocabulary using iana-media-type (#11 ) ->
- [x] `publication-type` using https://marketplace-api.sshopencloud.eu/api/vocabularies/publication-type (#20)
- [x] `technology-readiness-level` using a mix between EOSC and CESSDA concepts (#12 ) ->
- [x] `discipline` using subset of ÖFOS classification (#8 ) ->
- [x] `service-type` vocabulary to be determined (#13) ->
- [x] `intended-audience` using Training Discovery Toolkit and EOSC (#14) ->
- [x] `standard` using SSK vocabulary (#15)
- [x] `EOSC-resource-category` using EOSC categories (#16) ->
- [x] `keyword` turning the values we have into concepts (#18 ) 

notify @KlausIllmayer @vronk @vronk @egray523 @vronk @vronk
